Global:
  use_gpu: True
  epoch_num: 90
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: /content/drive/MyDrive/PaddleOCR/output/rec/rec_svtr_tiny_en/
  save_epoch_step: 1
  # evaluation is run every 315 iterations after the 0th iteration
  eval_batch_step: [0, 315]
  cal_metric_during_train: True
  pretrained_model: /content/drive/MyDrive/PaddleOCR/pretrain_models/rec_svtr_tity/best_accuracy.pdparams
  checkpoints:
  save_inference_dir: ./inference/SVTR
  use_visualdl: False
  infer_img: /content/drive/MyDrive/PaddleOCR/doc/imgs_words/vi/word_7.jpg
  # for data or label process
  character_dict_path: /content/drive/MyDrive/PaddleOCR/ppocr/utils/dict/vi_vietnam.txt
  character_type: vi
  max_text_length: 120
  infer_mode: False
  use_space_char: True
  save_res_path: /content/drive/MyDrive/PaddleOCR/output/rec/predicts_svtr_tiny.txt
  d2s_train_image_shape: [3, 48, 512]

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  epsilon: 0.00000008
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed
  one_dim_param_no_weight_decay: true
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 2

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
    name: STN_ON
    tps_inputsize: [32, 64]
    tps_outputsize: [48, 512]
    num_control_points: 20
    tps_margins: [0.05,0.05]
    stn_activation: none
  Backbone:
    name: SVTRNet
    img_size: [48, 512]
    out_char_num: 120
    out_channels: 192
    patch_merging: 'Conv'
    embed_dim: [64, 128, 256]
    depth: [3, 6, 3]
    num_heads: [2, 4, 8]
    mixer: ['Local','Local','Local','Local','Local','Local','Global','Global','Global','Global','Global','Global']
    local_mixer: [[7, 11], [7, 11], [7, 11]]
    last_stage: True
    prenorm: false
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /content/drive/MyDrive/PaddleOCR/dataset
    label_file_list:
    - ./dataset/train.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - SVTRRecAug:
          aug_type: 0 # or 1
      - SVTRRecResizeImg:
          character_dict_path: /content/drive/MyDrive/PaddleOCR/ppocr/utils/dict/vi_vietnam.txt
          image_shape: [3, 48, 512]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 32
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /content/drive/MyDrive/PaddleOCR/dataset
    label_file_list:
    - ./dataset/test.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - SVTRRecResizeImg:
          character_dict_path: /content/drive/MyDrive/PaddleOCR/ppocr/utils/dict/vi_vietnam.txt
          image_shape: [3, 48, 512]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 16
    num_workers: 2
